### ISSUE TITLE
contribute

### ISSUE THREAD

**Issue by horlathunbhosun** [borderlesshq/delivery-laravel#1]
Hello @Just4Ease   i would like to contribute to this laravel sdk for borderlesshq delivery anything i need ti join thanks

**Comment by Just4Ease** [comment]
Yes comrade, please proceed. 

Here's the slack channel
https://join.slack.com/t/delivery-os-community/shared_invite/zt-14w27j1pt-7Q~8M3ZRYD41BG_devhpag
